version: '3.9'

services:
  frontend:
    build: ./frontend
    ports:
      - "8000:8000"
    restart: always

  backend:
    build: ./backend
    ports:
      - "7000:7000"
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434
    restart: always

  ollama:
    image: ollama/ollama
    ports:
      - "11435:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./start-ollama.sh:/start-ollama.sh
    entrypoint: ["sh", "/start-ollama.sh"]
    restart: always


volumes:
  ollama_data:
